export const CSS_VARS = {
  "--argyros-bg": "#0c0c10",
  "--argyros-surface": "#151519",
  "--argyros-surface-hover": "#1e1e25",
  "--argyros-border": "#252530",
  "--argyros-text": "#e8e8ed",
  "--argyros-text-secondary": "#7a7a8a",
  "--argyros-text-dim": "#555565",
  "--argyros-accent": "#c8ff00",
  "--argyros-accent-hover": "#d4ff33",
  "--argyros-error": "#ff4d6a",
  "--argyros-warning": "#ffaa00",
  "--argyros-success": "#00d68f",
  "--argyros-radius": "20px",
  "--argyros-radius-sm": "14px",
  "--argyros-badge-bg": "#0a0a0e",
  "--argyros-font": "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
} as const;

export const LIGHT_OVERRIDES: Record<string, string> = {
  "--argyros-bg": "#ffffff",
  "--argyros-surface": "#f5f5f7",
  "--argyros-surface-hover": "#ebebef",
  "--argyros-border": "#d4d4dc",
  "--argyros-text": "#1a1a2e",
  "--argyros-text-secondary": "#6b6b7a",
  "--argyros-text-dim": "#9a9aaa",
  "--argyros-accent": "#1a1a2e",
  "--argyros-accent-hover": "#2d2d45",
  "--argyros-badge-bg": "#e8e8ed",
};
